#!/bin/bash

for i in $@; do :; done; url=$i

if [ "$url" = "" ]; then
	echo "Usage: alive <URL>"
	exit
fi

status=`curl -sL -o /dev/null -w %{http_code} $url`
if [ "$status" = "200" ]; then
	echo "`date --rfc-3339=second` $url ALIVE"
else
	echo "`date --rfc-3339=second` $url DEAD"
fi

